### DISCUSSION TITLE
InlineNotification text color is not displaying properly with CSS custom properties enabled

### DISCUSSION THREAD

**Discussion by tw15egan** [carbon-design-system/carbon#8257] [Help] [answered]
Help! My InlineNotification looks like this in dark mode

![inline notification](https://user-images.githubusercontent.com/50754824/112634968-9a585300-8e11-11eb-92c1-722c8991203d.png)

**Comment by tw15egan** [comment, marked as answer]
Based on an update in https://github.com/carbon-design-system/carbon/pull/7808, Notifications use the `component-token` approach. If you are enabling CSS custom properties, you will need to import the `theme` and `component-token` files before your component imports, like so:

```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

@import '~carbon-components/scss/globals/scss/theme';
@import '~carbon-components/scss/globals/scss/component-tokens';

@import '~carbon-components/src/components/tag/tag';
@import '~carbon-components/src/components/notification/notification';

:root {
  @include carbon--theme($carbon--theme--g100, true) {
    @include emit-component-tokens($tag-colors);
    @include emit-component-tokens($notification-colors);
  }
}
```
