### DISCUSSION TITLE
v11 Beta 2

### DISCUSSION THREAD

**Discussion by joshblack** [carbon-design-system/carbon#9723] [Release Feedback]
Have you tried out the v11 Beta 2 release and have any feedback? We'd love to hear it! From issues that you might have run into to questions you might have, feel free to post anything release-related here.

Thanks so much for your help! We really appreciate it 🙏

**Comment by joshblack** [comment]
Unable to get the `type.default-type()` mixin from `@carbon/react/scss/type`

**Comment by joshblack** [comment]
It's hard to know what the "new token" to use is when trying to build something out (e.g. what is link-01 now supposed to be)

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/134547113-a325f5cb-89b2-4fe9-837d-047c917b3811.png)

The fonts in dark mode seem too thin, this could be related to text rendering

![image](https://user-images.githubusercontent.com/3901764/134547247-88505b09-fed5-45af-981e-a4157339a109.png)

**Comment by joshblack** [comment]
I miss the "auto span" columns from flexbox 😞

**Reply by tay1orjones** [reply]
Yeah, it's a big change. We could always try to reimplement the auto span behavior. Grid could be modified to apply props to children columns that aren't given any `sm`/`md`/etc. prop(s). This would make the default column span behavior quite different between `@carbon/react` and `@carbon/styles` though.

**Reply by ConradSchmidt** [reply]
If it is not supported, please remove it from the [documentation](https://v11.carbondesignsystem.com/migrating/guide/develop#css-grid-breaking). I was a bit confused by the result ;)

**Comment by joshblack** [comment]
We should make sure to include a solid snippet that people can bring in so they don't have to worry about how to import things from styles

**Comment by joshblack** [comment]
@jnm2377 brought up a great point that we should make more "starter" or "sample apps" that show how to use different parts of Carbon

@theiliad brought up dashboard as a great example for this

**Comment by abbeyhrt** [comment]
It looks like any component that uses list box under the hood `Multiselect`, `Combobox`, and `Dropodown` doesn't have their styles exported through `@carbon/react`

**Comment by tay1orjones** [comment]
My unfamiliarity with sass module namespaces tripped me up. When all the styles are brought in at once, the namespace is automatically the ending name of the _package_. I didn't know this!

```scss
// ❌ does not work
@use "@carbon/react";
main {
  background: $background;
}

// ❌ does not work
@use "@carbon/react";
main {
  background: theme.$background;
}

// ✅ works! (namespace automatically inferred from package name)
@use "@carbon/react";
main {
  background: react.$background;
}

// ✅ also works!
@use "@carbon/react" as carbon;
main {
  background: carbon.$background;
}

// ✅ also also works!
@use "@carbon/react" as *;
main {
  background: $background;
}
```

**Comment by tay1orjones** [comment]
I tried to use `Theme` and `Layer` to play with switching themes and inline theming, but ran into the issue where the components were applying classes with the old `bx` prefix instead of `cds`, so no styles were applied. 

This should be fixed by https://github.com/carbon-design-system/carbon/pull/9728 🎉

**Comment by sstrubberg** [comment]
We should lift the usage of Carbon Styles for the components and surface them in the website docs. When I imported button, I was tripped up on why there were no styles. Until i went and found [this](https://github.com/carbon-design-system/carbon/tree/main/packages/styles#usage)

**Reply by theiliad** [reply]
maybe a JS util that shows a message when styles aren't present... in the console?

**Comment by janhassel** [comment]
It seems that the subgrid logic breaks when one uses column offsets.

Tested with `@carbon/react@0.6.0`

```jsx
<Grid>
  <Column sm={4} md={{ span: 6, offset: 1 }} lg={{ span: 8, offset: 1 }}>
    Full
    <Grid>
      <Column sm={2} md={3} lg={4}>
        Half
      </Column>
      <Column sm={2} md={3} lg={4}>
        Half
      </Column>
    </Grid>
  </Column>
</Grid>
```

I'd expect the above code to always show two columns next to each other with equal widths.
However, these are the results:

| Breakpoint | Result |
| :- | :- |
| sm | ![image](https://user-images.githubusercontent.com/28265588/136042081-99533d88-2b3c-4fc7-9a7c-a3b01afe5f05.png) |
| md | ![image](https://user-images.githubusercontent.com/28265588/136042141-936faf0c-5aed-4f19-bd1d-08353967dbb6.png) |
| lg | ![image](https://user-images.githubusercontent.com/28265588/136042176-752bd443-2ec2-42da-bec3-bf8db6161863.png) |

**Reply by joshblack** [reply]
cc @tay1orjones

**Comment by ConradSchmidt** [comment]
I wasn't really able to apply the inline-theming by using the `Theme` component:
1. the `cds--white` class didn't have any css rules
* so I imported the `@carbon/styles/scss/zone`
![image](https://user-images.githubusercontent.com/3808948/136056147-97ddd806-e948-4c5f-9c4c-91bb6c977ea2.png)

2. then the `Tile` component didn't use the `--cds-layer-01` variable for its background
* so I added a `Layer` component around it
![image](https://user-images.githubusercontent.com/3808948/136056255-7fc3fa82-0372-4006-bfa1-94e18d9d8ed4.png)

3. then the text color of the tiles content was white on white
* so I added a css class to set the `color` to `text-primary`
![image](https://user-images.githubusercontent.com/3808948/136056333-2f7e82ac-8ea2-49a8-925d-037090278f89.png)

I'm not sure if my setup is wrong or I missed something...
My exception would be that none of these steps should be necessary to get inline theming working.

**Comment by ConradSchmidt** [comment]
When using the CSS-Grid the breakpoint definitions were a bit confusing to me, because I was used to the v10 ones. Currently you have to define all break points otherwise its hard to predict how they behave (based on the [documentation](https://v11.carbondesignsystem.com/migrating/guide/develop#css-grid-breaking)).

## Only `md` definition

  ```html
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
      <Column md={1}>1 of 8</Column>
  ```  

![image](https://user-images.githubusercontent.com/3808948/136057793-0a7aa59a-fac6-413a-8392-e640ae91ff94.png)

It applies the 1 MD Column definition to the LG breakpoint, which I didn't expect. Because when I change it to `md={2}` it will fill the 16 Cols.  In v10 a `md-2` would behave like a `lg-8` (upwards) and `sm-4` (downwards) if not defined differently.  

## Full definition

```html
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
      <Column sm={1} md={1} lg={2}>1 of 8</Column>
```

![image](https://user-images.githubusercontent.com/3808948/136058453-3a28029e-5909-45d6-bf3b-07610d92fb41.png)

This seems to me a bit excessive, but maybe intended.

**Comment by ConradSchmidt** [comment]
In order to setup a `g100` theme I needed help from @janhassel, otherwise I wouldn't figured it out:
```scss
@use '@carbon/styles/scss/compat/themes' as compat;
@use '@carbon/styles/scss/themes';
@use '@carbon/styles/scss/theme' with (
  $fallback: themes.$g100,
  $theme: compat.$g100,
);
@use '@carbon/styles/scss/zone';
@use '@carbon/styles';

:root {
  @include theme.theme(themes.$g100);
}

body {
  background-color: theme.$background;
  color: theme.$text-primary;
}
```

This seems a bit complicated to me (maybe a helper function could solve that), because before it were 1-2 lines of scss.
Documentation would also help (when released), but I'm concerned that this could put off people (beginners or teams who migrate).

Related to this: when using Carbon I always have to write some code to have `g100` apply for dark mode users and `white` for light-mode users. It would be cool, to have a setting to do this automatically
