### ISSUE TITLE
[Bug]: Tooltip link color gets overridden when within DataTable

### ISSUE THREAD

**Issue by brunnerh** [carbon-design-system/carbon#10182]
### Package

carbon-components

### Browser

Chrome

### Package version

v10.48.0 (via carbon-components-svelte)

### Description

The `Tooltip` component has an inverted color scheme, so `Link` colors within it also get inverted. However, this style can be overridden when the `Tooltip` is within a `DataTable` and the row is directly or indirectly hovered.

[Link color inversion in Tooltip](https://github.com/carbon-design-system/carbon/blob/c017826bc77864fbe8af7b8ac0c9039d29c9c630/packages/components/src/components/tooltip/_tooltip.scss#L453):
```scss
  .#{$prefix}--tooltip {
    // ...
    .#{$prefix}--link {
      color: $inverse-link;
      font-size: rem(14px);
```

[DataTable override on hover](https://github.com/carbon-design-system/carbon/blob/c017826bc77864fbe8af7b8ac0c9039d29c9c630/packages/components/src/components/data-table/_data-table-core.scss#L96):
```scss
  .#{$prefix}--data-table tbody tr:hover td .#{$prefix}--link,
  .#{$prefix}--data-table tbody tr:hover th .#{$prefix}--link {
    color: $link-secondary;
  }
```

### Screenshots

Without hover:
![image](https://user-images.githubusercontent.com/834235/143765131-f17b4393-5186-4d67-8a68-e3f1af600db6.png)

With hover:
![image](https://user-images.githubusercontent.com/834235/143765140-8c6e3f59-b579-464c-acf7-a1b4ff2e5cad.png)

### Steps to reproduce

- Add `DataTable`
- Add `Tooltip` with `Link` to one of the cells
- Open tooltip and hover row or tooltip popup

[Svelte REPL](https://svelte.dev/repl/db0d79b1e9494ec9a108be63b842005e?version=3.44.2)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems
