### ISSUE TITLE
[Feature/Fix]: Datatable stickyHeader - css only 

### ISSUE THREAD

**Issue by salvoravida** [carbon-design-system/carbon#10560]
### Summary

The current implementation of Datatable with stickyHeader is quite different from the normal one, and IMHO too over-engineered. (maybe for support old IE11?), with many limitations such as fixed columns width.
Instead, I founded a quite easy solution based only on CSS:

```css
   .bx--data-table-content {
      max-height: 100%; //support sticky
      thead,
      th {
         position: sticky;
         top: 0;
         z-index: 2;
      }
   }
```

https://caniuse.com/?search=sticky

It should support all browsers> 2018 (th is used on Chrome<91 (2021)

Let me know if you'd like a PR for this.

Regards! 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
