### ISSUE TITLE
[Bug]: Zebra styling is broken

### ISSUE THREAD

**Issue by SeanAllanMacKay** [carbon-design-system/carbon#10711]
### Package

carbon-components

### Package version

v10.52.0

### Description

The zebra styling in the CDN CSS is currently broken. We are loading it from [your CDN here](https://unpkg.com/carbon-components@10.52.0/css/carbon-components.min.css)

```css
.bx--data-table--zebra tbody tr:not(.bx--parent-row):nth-child(even) td{
  border-top:1px solid #fff;
  border-bottom:1px solid #fff;
  background-color:#fff
}
```

Previously (and currently in your examples [here](https://www.carbondesignsystem.com/components/data-table/usage#live-demo)) the values that are now `#fff` in the code above were correctly set to `var(--cds-ui-03,#e0e0e0);`

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-datatable--usage

### Steps to reproduce

I linked to your first party Storybook, loading from the same CDN. Check the `Zebra row styles (useZebraStyles)` knob and the styles will be incorrect.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems
