### ISSUE TITLE
[Bug]: Some CSS variables in @carbon/styles use a different prefix

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#11271]
### Package

@carbon/styles

### Package version

1.1.0

### Description

When compiling `@carbon/styles` to a CSS file, I set a custom prefix "bx."

```css
@use '@carbon/styles' with (
  $prefix: 'bx',
);
```

I'm using `sass` and `postcss` to compile the SASS:

```js
const { css } = sass.renderSync({
  file,
  outFile,
  includePaths: ["node_modules"],
});

const prefixed = await postcss([
  autoprefixer({
    overrideBrowserslist: ["last 1 version", "ie >= 11", "Firefox ESR"],
  }),
]).process(css, { from: undefined });
```

All the selector names are correctly updated. However, there are some instances where some properties use the default `--cds` prefix.

From what I can tell, they are mostly typography-related. Note how the class name has the correct prefix, but the property values have `--cds`.

```css
.bx--form-item {
  font-size: var(--cds-body-compact-01-font-size, 0.875rem);
  font-weight: var(--cds-body-compact-01-font-weight, 400);
  line-height: var(--cds-body-compact-01-line-height, 1.28572);
  letter-spacing: var(--cds-body-compact-01-letter-spacing, 0.16px);
  display: flex;
  flex: 1 1 auto;
  flex-direction: column;
  align-items: flex-start;
}
```

### CodeSandbox example

N/A

### Steps to reproduce

```js
const { css } = sass.renderSync({
  file: "css/index.scss",
  outFile: "css/index.css",
  includePaths: ["node_modules"],
});

const prefixed = await postcss([
  autoprefixer({
    overrideBrowserslist: ["last 1 version", "ie >= 11", "Firefox ESR"],
  }),
]).process(css, { from: undefined });

fs.writeFileSync("css/index.css", prefixed.css);
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems
