### ISSUE TITLE
[Feature Request]: Add @carbon/type mixin for font-style

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#15131]
### The problem

@carbon/type has nice mixins for things like `font-weight`, so I can write:

```scss
@use '@carbon/type';
...
.keyword,
.function {
  font-weight: type.font-weight("semibold");
}
```

However, AFAICT there's nothing equivalent for `font-style`, so I have to do something weird like this:

```scss
@use '@carbon/type';

// Get Carbon definition of "italic": cds--type-italic.  Wish there was a more direct way to set the font-style.
@include type.type-classes();

.comment {
  @extend .cds--type-italic;
}
```

### The solution

I'd like a similar function so I can do:

```scss
@use '@carbon/type';
...
.comment {
  font-style: type.font-style("italic");
}
```

If you're wondering:

* Why am I micro-managing styling instead of using the predefined settings?   Because this is for a SQL syntax highlighter.
* Why don't I just type `font-style: italic`?  To avoid errors from [stylelint-plugin-carbon-tokens](https://github.com/carbon-design-system/stylelint-plugin-carbon-tokens).
* Why don't I just directly add the `cds--type-italic` class to my `<span>` instead of using `@extend`?  It was just a bit hard to write the JS code to do that.  My markup is generated dynamically.

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
