### ISSUE TITLE
[Question]: Typography and Reset question

### ISSUE THREAD

**Issue by omarabid** [carbon-design-system/carbon#15230]
### Question for Carbon

Hello,

I'm using `@carbon/react` for a project and using `@use "@carbon/react"` in my main scss file to import styles. This does work (I think?), however, I am at loss on how to style contents (or if I should implement the styles myself?).

For example, Headers (H1, H2, etc...) comes with styles. However, UL and OL do not. There is also no margin/padding between P elements.

1. I am wondering if I am missing a configuration somewhere or this is the expected behavior.
2. I wonder if it is possible to increase the font (rem) for a particular section (and its children).

Thanks!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

**Comment by tay1orjones** [comment]
Hey @omarabid, great question! This is because rather than target specific tag-level elements, we apply styles based on class names provided to those elements. These specifically target the DOM structure specified in the components available through `@carbon/react`.

So for instance, `ul` and `ol` have no styles by default, but if you add the class names to match what's in the component source, it'll be styled appropriately

https://github.com/carbon-design-system/carbon/blob/a34df27dbddf57d8ced5f08a83b0ad225f1daa5f/packages/react/src/components/OrderedList/OrderedList.tsx#L26-L36

It is possible to add global styling if you'd prefer using the tokens provided, for instance:

```scss
@use '@carbon/react/scss/spacing' as *;
@use '@carbon/react/scss/type' as *;

// Add some unified spacing between `p` tags:
p { 
  margin-block-end: $spacing-01
}

// Modify the type settings for an element or parent container of part of your app:
.my-area-with-larger-text {
  @include type-style('heading-06');
}
```

Hope this helps!
