### ISSUE TITLE
[Feature Request]: DataTable ability to add (non-AI) slugs to column headers

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon#17303]
### The problem

Our app needs to add info tooltips to column headers:

<img width="904" alt="infoIcon" src="https://github.com/user-attachments/assets/2a731a55-98d9-4eba-9534-8b67594396d7">
<img width="902" alt="info icon with tooltip" src="https://github.com/user-attachments/assets/331ccaf2-f4e4-4a1e-99b1-1b4511eddb55">

So I want a DataTable option to do that.

### Workaround

DataTable (and @carbon/ibm-products' Datagrid) support adding "AI labels" to column headers and rows.

But then Carbon inserts a  blue gradient in the data cells, and the blue bar at the top:

<img width="1242" alt="aiLabel" src="https://github.com/user-attachments/assets/5a2706a3-3e3d-43c4-b406-416e3caa2726">

In order to add a slug without the table style changing,  I need to disable Carbon's AI styling.  This is not trivial, because DataTable has styling for selected rows, hovered rows, hovered + selected rows, child rows, etc.   This is what worked for me but it's not complete:

```scss
// Override the top blue line and background gradient that Carbon applies to <th> and <td> with slugs (i.e.
// the headers and cells in columns where we have the (i) icon).  We don't want any special styling there.
th {
  background: themes.$layer-accent !important;
  box-shadow: none !important;
}
td {
  background: themes.$layer !important;
}
:global(.#{prefixes.$carbon}--data-table--selected) td {
  background: themes.$layer-selected !important;
}
tr:hover > td {
  background: themes.$layer-hover !important;
}
.#{prefixes.$carbon}--data-table--selected:hover > td {
  background: themes.$layer-selected-hover !important;
}
```

### The solution

Technically speaking, you could implement this by only enabling the blue styling for AI slugs, for example:

```tsx
<TableCell aiStyling>
```

But I want to be clear that _I am not asking to change the styling_.  I am asking for the opposite: To add a slug to column headers _without changing the table styling_.

### Application/PAL

IKC

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
