### ISSUE TITLE
[Bug]: Layer example and README need update

### ISSUE THREAD

**Issue by IgnacioBecerra** [carbon-design-system/carbon#17757]
### Package

@carbon/web-components

### Browser

Chrome

### Package version

latest

### Description

The Stackblitz example for the Web Component version of Layer needs to be updated, as well as the README for easier adopter use.

### Reproduction/example

https://stackblitz.com/github/carbon-design-system/carbon/tree/main/packages/web-components/examples/components/layer?file=src%2Findex.js

### Steps to reproduce

Check the Stackblitz and notice the color is the same for all layers.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by IgnacioBecerra** [comment]
This can be fixed by editing the Stackblitz example .scss file with the following:
```scss
@use '@carbon/styles/scss/spacing' as *;
@use '@carbon/styles/scss/theme' as *;

.example-layer-test-component {
  padding: $spacing-05;
  background: $layer;
  color: $text-primary;
}
```

Also it would be helpful to update the README to add a note stating the need for the `background: $layer` to be added within the first slotted div inside the layer component.
