### ISSUE TITLE
Add doumentation about grid components

### ISSUE THREAD

**Issue by nielspardon** [carbon-design-system/carbon#21]
While there's a description of Grids in the Style section I can't find any information on how to use the grid in the components section. Can you add this information please?

**Comment by gmosx** [comment]
Not only that, I am not able to find any grid-related .scss files.

**Comment by chrisdhanaraj** [comment]
Heyo - sorry about the delay here, but the system as it is does not provide grid scss files (beyond a grid-container for overall page spacing). Our rationale for that was that - given our browser matrix is the evergreen browsers + IE11 - developers have access to `flexbox` to enable layout.

However, having said that, we've been asked about a grid system for a while now, so we're looking into rolling out a simple grid structure

**Comment by gmosx** [comment]
Maybe you could add a 'usage' section that describes how to use CSS Flexbox to implement the grid?

**Comment by hellobrian** [comment]
> we've been asked about a grid system for a while now, so we're looking into rolling out a simple grid structure - @chrisdhanaraj 

☝️ When that happens, then you'll see code and docs on how to use the grid in code.

Right now, the only thing we do have in code (`SCSS`) is the handling of outer margins at major breakpoints. 

![image](https://cloud.githubusercontent.com/assets/4185382/25146250/da26a000-2438-11e7-9566-8a32788c9b69.png)

### Usage

```scss
.app-container {
  @include grid-container;
}
```

### [Source Code](https://github.com/carbon-design-system/carbon-components/blob/321b63e2d553b3f583af234b7c67b4f0a115c3d7/src/globals/scss/_layout.scss#L54-L63)

```scss
// carbon-components/src/globals/scss/_layout.scss

@mixin grid-container {
  width: 100%;
  padding-right: padding(mobile);
  padding-left: padding(mobile);

  @include breakpoint(bp--xs--major) {
    padding-right: padding(xs);
    padding-left: padding(xs);
  }
}
```
