### ISSUE TITLE
Finalize and update motion duration tokens

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon#2105]
Duration tokens are being updated for v10 to include more duration options beyond the the default two `$transition--base` and `$transition--expansion`. 

### Task
- [x] finalize naming of duration tokens
- [x] update duration tokens through out component repo

Then, update duration tokens on the website to expose usage and guidance. https://github.com/carbon-design-system/carbon-website/issues/1301

**Comment by shixiedesign** [comment]
### Token naming: 
New duration tokens proposal: 

```css
$transition--fast-01: 70ms;
$transition--fast-02: 110ms;
$transition--moderate-01: 150ms;
$transition--moderate-02: 240ms;
$transition--slow-01: 400ms;
$transition--slow-02: 720ms;

$transition--base: $transition--fast-02;
$transition--expansion: $transition--moderate-02;
```

Alternative duration token proposal:$transition-fast-short: 100ms;
```css
$duration-01: 70ms;
$duration-02: 110ms;
$duration-03: 150ms;
$duration-04: 240ms;
$duration-05: 400ms;
$duration-06: 720ms;
```

### Token values:

![image](https://user-images.githubusercontent.com/15144993/54395287-6cb26e00-467d-11e9-981b-91a0682cbefc.png)

**Comment by shixiedesign** [comment]
### Notable feedback / comments

![image](https://user-images.githubusercontent.com/15144993/54395456-d9c60380-467d-11e9-952b-03543b697a34.png)

![image](https://user-images.githubusercontent.com/15144993/54395368-a7b4a180-467d-11e9-970a-a8006f5b61bc.png)

**Comment by shixiedesign** [comment]
### Conclusion 
Motion tokens are relatively new to users and less familiar as spacing tokens, so the decision leans towards keeping the speed descriptors `fast`, `moderate` and `slow`. Below set of token names should be used in v10. No dispute with values, so keeping as is. 

```css
$duration--fast-01: 70ms;
$duration--fast-02: 110ms;
$duration--moderate-01: 150ms;
$duration--moderate-02: 240ms;
$duration--slow-01: 400ms;
$duration--slow-02: 720ms;

$transition--base: $duration--fast-02;
$transition--expansion: $duration--moderate-02;
```

**Comment by asudoh** [comment]
@shixiedesign Thank you for bringing this up! Seems that `carbon-components` has below, identical to yours except the variable name prefix:

```scss
$transition--fast-01: 70ms;
$transition--fast-02: 110ms;
$transition--moderate-01: 150ms;
$transition--moderate-02: 240ms;
$transition--slow-01: 400ms;
$transition--slow-02: 720ms;

...

@if feature-flag-enabled('components-x') {
  ...
  $transition--base: $transition--fast-02;
  $transition--expansion: $transition--moderate-01;
}
```

Does it mean we'd go with renaming the variables...?
