### ISSUE TITLE
Tooltip label is too dark in v10

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2139]
See screenshot. `"carbon-components": "9.84.12"`.

`bx--tooltip__label` color is too dark. The Carbon website and Storybook examples do not use this class.

I'm assuming this class name has not been deprecated since it's in the CSS. Either the color didn't get updated with the v10 tooltips went dark? Or the wrong color token is getting used?

![image](https://user-images.githubusercontent.com/1691245/54645424-fbeac780-4a69-11e9-87f0-0f475327df65.png)

**Comment by asudoh** [comment]
Seeing the following in the-carbon-components.netlify.com:

```css
.bx--tooltip--definition__bottom p, .bx--tooltip--definition__top p {
  ...
  color: #ffffff;
}
```

So I think the problem has been fixed.
