### ISSUE TITLE
[UI Shell]: IE11 reset CSS needs display:block on <main> elements

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon#2789]
Without `display:block` on main:
![image](https://user-images.githubusercontent.com/1691245/58108556-ae95ee00-7bb1-11e9-9d15-99fb2b1e820b.png)

With `display:block` on main:
![image](https://user-images.githubusercontent.com/1691245/58108664-d9804200-7bb1-11e9-92f3-1ce262e3423d.png)

Normalize has:

https://necolas.github.io/normalize.css/latest/normalize.css

```css
/**
 * Render the `main` element consistently in IE.
 */

main {
  display: block;
}
```

I don't see `main` in `_css--reset.scss`.
