### ISSUE TITLE
[Data-table] - sortable header overflow styles aren't correct 

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon#2830]
When there's no overflow, each of the sortable headers should align as follows:

- default: top aligned but looks like middle align w/o overflow
- compact: top aligned but looks like middle align w/o overflow
- short: top aligned but looks like middle align w/o overflow
- tall: top aligned 

`default`
<img width="918" alt="Screen Shot 2019-05-23 at 2 22 36 PM" src="https://user-images.githubusercontent.com/32556167/58284673-b780ee00-7d70-11e9-88bd-ba9d81528376.png">
<img width="917" alt="Screen Shot 2019-05-23 at 2 22 48 PM" src="https://user-images.githubusercontent.com/32556167/58284675-b780ee00-7d70-11e9-9b2f-e1abcaa7804b.png">
`compact`
<img width="922" alt="Screen Shot 2019-05-23 at 2 21 49 PM" src="https://user-images.githubusercontent.com/32556167/58284671-b6e85780-7d70-11e9-97f1-2fb864788b11.png">
`short`
<img width="925" alt="Screen Shot 2019-05-23 at 2 20 51 PM" src="https://user-images.githubusercontent.com/32556167/58284669-b6e85780-7d70-11e9-98ee-97d47e71ac2c.png">
`tall`
<img width="928" alt="Screen Shot 2019-05-23 at 2 18 34 PM" src="https://user-images.githubusercontent.com/32556167/58284666-b6e85780-7d70-11e9-9cb7-6bc7c1d590c5.png">

With overflow the sortable headers should all align at the **top**.

However, at the moment, because of the `display:flex` that the sort button is receiving in order to make the height fluid/responsive, when there is overflow (text-wrap), the header label and icons aren't aligning properly. 

Design decided the best solution would be to have it multi-line (max 2 lines) truncate on overflow. 

This was possible in tall header by adding the following:
```css
  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th {
    height: rem(64px);
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort {
    padding-top: 0;
    padding-bottom: 0;
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort svg {
    align-self: flex-start;
    top: $spacing-03;
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort .#{$prefix}--table-header-label {
    align-self: flex-start;
    position: relative;
    top: rem(-8px);
    max-height: 3rem;
    display: -webkit-box; // weird text truncation style used
    -webkit-line-clamp: 2; // because we need text to wrap
    -webkit-box-orient: vertical; // can't use white-space: nowrap
  }
```

However, trying to have multi line text truncation for `short`, `compact` and `default` table didn't seem to work correctly for several reasons.

1) styles required for multi line truncation were cutting off long letters like `p, y, j`. 
2) when setting ` -webkit-line-clamp: 2; ` the header label was no longer top-aligning on overflow. We were able to get it to align in tall sortable header by adding ` max-height: 3rem;`, but for `compact`, `short` and `default` tables, the header was only aligning if the max-height was  `1.5rem`, `2rem` and `2.75rem`. This didn't allow for 2 lines of text, however, rather just 1 line.

Need to figure out how to properly align the header labels with text overflow (whether it's text wrap or text truncation).

<img width="955" alt="Screen Shot 2019-05-23 at 2 19 04 PM" src="https://user-images.githubusercontent.com/32556167/58284667-b6e85780-7d70-11e9-9996-88af75a607a1.png">
<img width="747" alt="Screen Shot 2019-05-23 at 2 20 21 PM" src="https://user-images.githubusercontent.com/32556167/58284668-b6e85780-7d70-11e9-8ce9-5007fc9f5ec4.png">
<img width="623" alt="Screen Shot 2019-05-23 at 2 21 25 PM" src="https://user-images.githubusercontent.com/32556167/58284670-b6e85780-7d70-11e9-9d08-6b0647d188b6.png">
<img width="573" alt="Screen Shot 2019-05-23 at 2 22 12 PM" src="https://user-images.githubusercontent.com/32556167/58284672-b780ee00-7d70-11e9-8912-553ecda514bd.png">
<img width="636" alt="Screen Shot 2019-05-23 at 2 23 11 PM" src="https://user-images.githubusercontent.com/32556167/58284676-b780ee00-7d70-11e9-9549-cae9277f5736.png">

What sortable header w/ overflow looks like without text truncation/max height (note how it's center aligned instead of aligned with the checkbox).
<img width="605" alt="Screen Shot 2019-05-23 at 3 42 08 PM" src="https://user-images.githubusercontent.com/32556167/58284967-7937fe80-7d71-11e9-82d3-7393b7a23328.png">

**Comment by jnm2377** [comment]
Initially tried to implement this code in the `_data-table-sort.scss` in this PR: https://github.com/carbon-design-system/carbon/pull/2388. Didn't have enough time to focus on debugging this with UI shell work, so removed the code and just focused on non-sort size styles since the sortable header alignment bug seemed to be present on all of examples (including default) not just size variation. 

```css

  // -------------------------------------
  //Th > Button > Header Label (default)
  // -------------------------------------
  .#{$prefix}--data-table--sort th .#{$prefix}--table-sort .#{$prefix}--table-header-label {
    max-height: 2.75rem;
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box; // weird text truncation style used
    -webkit-line-clamp: 1; // because we need text to wrap
    -webkit-box-orient: vertical; // can't use white-space: nowrap
  }

  //----------------------------------------------------------------------------
  // Compact, Short, Tall Sortable
  //----------------------------------------------------------------------------
  // Sortable compact
  .#{$prefix}--data-table--compact.#{$prefix}--data-table--sort th {
    height: rem(24px);
  }

  .#{$prefix}--data-table--compact.#{$prefix}--data-table--sort th .#{$prefix}--table-sort {
    padding-top: 0;
    padding-bottom: 0;
  }

  .#{$prefix}--data-table--compact.#{$prefix}--data-table--sort th .#{$prefix}--table-sort .#{$prefix}--table-header-label {
    max-height: 1.5rem;
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box; // weird text truncation style used
    -webkit-line-clamp: 1; // because we need text to wrap
    -webkit-box-orient: vertical; // can't use white-space: nowrap
  }

  // Sortable Short
  .#{$prefix}--data-table--short.#{$prefix}--data-table--sort th {
    height: rem(32px);
  }

  .#{$prefix}--data-table--short.#{$prefix}--data-table--sort th .#{$prefix}--table-sort {
    padding-top: 0;
    padding-bottom: 0;
  }

  .#{$prefix}--data-table--short.#{$prefix}--data-table--sort th .#{$prefix}--table-sort .#{$prefix}--table-header-label {
    max-height: 2rem;
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box; // weird text truncation style used
    -webkit-line-clamp: 1; // because we need text to wrap
    -webkit-box-orient: vertical; // can't use white-space: nowrap
  }

  // Sortable Tall
  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th {
    height: rem(64px);
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort {
    padding-top: 0;
    padding-bottom: 0;
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort svg {
    align-self: flex-start;
    top: $spacing-03;
  }

  .#{$prefix}--data-table--tall.#{$prefix}--data-table--sort th .#{$prefix}--table-sort .#{$prefix}--table-header-label {
    align-self: flex-start;
    position: relative;
    top: rem(-8px);
    max-height: 3rem;
    display: -webkit-box; // weird text truncation style used
    -webkit-line-clamp: 2; // because we need text to wrap
    -webkit-box-orient: vertical; // can't use white-space: nowrap
  }

```
