### ISSUE TITLE
[TableToolbarSearch]: persistant mode css overwritten

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#3108]
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

I'm using the react component `TableToolbarSearch` inside DataTable/TableContainer/TableToolbar.

I've switched on the `persistant` option.

*The following CSS problem occurs:*<br/>
The correct _width_ of 100% for the persistant css modifier gets overwritten by the _width_ of 3rem, which is defined in the toolbar-action class.

I've fixed that temporary by using this ugly work around:

```scss
.bx--table-toolbar {
  .bx--toolbar-action {
    &.bx--toolbar-search-container-persistant {
      width: 100%;
    }
  }
}
```
