### ISSUE TITLE
[TableToolbarSearch] `value` overwritten by empty state

### ISSUE THREAD

**Issue by IOIO72** [carbon-design-system/carbon#3170]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react` `v7.3.2`

## Detailed description

I’m trying to set a default value for the `DataTable` / `TableToolbarSearch` input field. Usually the props are passed down to the child components. In this case it’s the `Search` component, which offers the `defaultValue` and `value`. Unfortunately the `TableToolbarSearch` component initializes the `value` property by setting an empty state. Therefore, I can’t set a default value.

Related code line:
https://github.com/carbon-design-system/carbon/blob/3dabe8fd1272896f7c7d33ab2a451c7e15f5f90f/packages/react/src/components/DataTable/TableToolbarSearch.js#L46

## Steps to reproduce the issue

[![Edit codesandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/codesandbox-82cvg?fontsize=14)

## Additional information

Note: The Sandbox contains a little CSS bug fix for persistant mode, which I've described in #3108 already:

```css
      .bx--table-toolbar
        .bx--toolbar-action.bx--toolbar-search-container-persistant {
        width: 100%;
      }
```
