### ISSUE TITLE
Button has top level ampersand: causing compilation error

### ISSUE THREAD

**Issue by hybridindie** [carbon-design-system/carbon#3294]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

The button component has a base-level ampersand causing the following compilation error. 

`Sass::SyntaxError: Base-level rules cannot contain the parent-selector-referencing character '&'.`

This references the following class on line 216 that I also don't see any documentation for. 

```scss
  &.#{$prefix}--btn--field {
    height: 40px;
    min-height: 40px;
    padding: $button-padding-field;
  }
```

Commenting this out does resolve the problem but that is nothing more than a band-aid.
