### ISSUE TITLE
Update icon sizing to be based off of a relative unit instead of absolute

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3496]
Currently our icons are sized using the `px` unit, instead we want to use a relative unit like `rem` (or even `em`) so that our icons scale up as our text increases, either through user preferences or other use-cases like theming.

**Comment by mattrosno** [comment]
@joshblack `em` seems to make the most sense here so it's relative to its container's font size, not root element font size. That way we can achieve component-level theming.

This issue isn't about variable strategy, but it'd be great to set via a variable for easy theming, in case font-size and icon size theming changes aren't proportional.

```scss
$accordion-icon-size: 1em !default;

.bx--accordion__arrow {
  height: $accordion-icon-size;
  width: $accordion-icon-size;
}
```

CC @photodow
