### ISSUE TITLE
Generate release changelog from GitHub Action

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3955]
We should use existing work in `@carbon/cli` to update our release process to automatically publish changelogs when we push up a tag.

GitHub Actions can be used to do this, and we can create custom actions in our own project to help out with this. At a high-level, this might look like:

1. Creating a workflow for generating the changelog on git tag push

This would live under `.github/workflows/changelog.yml` (or `release.yml`) and would look like:

```yml
name: Publish Changelog for Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: Install dependencies
        run: yarn install --offline
      - name: Build project
        run: yarn build
      # Reference for uses path:
      # https://help.github.com/en/articles/configuring-a-workflow#referencing-actions-in-your-workflow
      - name: Publish changelog
        run: ./actions/publish-changelog
```

Inside of `./actions/publish-changlog` we should define a custom action with `action.yml` following the guidance set in: https://help.github.com/en/articles/metadata-syntax-for-github-actions

There are templates to help guide what we could write in JavaScript, namely: https://github.com/actions/javascript-action
