### ISSUE TITLE
Determine CSS Custom Property Integration

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#3967]
## Enabling this feature

Couple of options:

- Introduce capabilities behind a feature flag, possibly `use-custom-properties`
- Introduce capabilities with appropriate fallback, meaning:

```scss
.selector {
  color: #000000;
  color: var(--token-01, #000000);
}
```

Wrapping behind a feature flag would mean complicating authoring logic, potentially, but could be encapsulated by helper mixins/functions (although not ideal).

## Writing this feature

The general strategy for CSS Custom properties will most likely output:

```scss
.selector {
  color: #000000;
  color: var(--token-01, #000000);
}
```

We want to do this so that browsers that do not support CSS Custom Properties will use the correct fallback value. However, we will probably want to author this feature in a different way. Some ideas:

```scss
// Option 1: specify token directly with no fallback, use build step
// to generate correct output
.selector {
  color: var(--token-01);
}

// Option 2: specify token and fallback, use build step to generate correct output
// drawback is that it could be error prone when authoring, may need lint rule
.selector {
  color: var(--token-01, $token-01);
}

// Option 3: use a helper function to output `var(--token-01, $token-01)`
// and a build step for correct output
.selector {
  // Name TBD
  color: some-function(token-01);
}

// Option 4: use a helper mixin to output the correct properties with no build step
.selector {
  // Name TBD
  @include some-mixin(token-01);
}
```

## Theming support

We want to support top-level theming and zone theming. Top-level theming should be a static transform (meaning no need to set custom properties). Zone theming will need to set custom properties. While subtle, the difference would be:

```scss
// Input
$carbon--theme: (
  token-01: #ffffff,
);
@include carbon--theme($carbon--theme);

.selector {
  color: var(--token-01, $token-01);
}

// Output
.selector {
  color: #ffffff;
  color: var(--token-01, #ffffff);
}
```

```scss
// Input
$light-theme: (
  token-01: #ffffff,
);

// Specify light theme as default
$carbon--theme: $light-theme
@include carbon--theme($carbon--theme);

.selector {
  color: var(--token-01, $token-01);
}

// Scope dark mode to `.dark` selector
$dark-theme: (
  token-01: #ffffff,
);
.dark {
  @include carbon--theme($dark-theme);
}

// Output
.selector {
  color: #ffffff;
  color: var(--token-01, #ffffff);
}

.dark {
  --token-01: #000000;
}
```

**Comment by joshblack** [comment]
cc @emyarod any thoughts on above? Figured we could start planning this implementation, let me know if I'm missing any details that would be helpful 👍

**Comment by elizabethsjudd** [comment]
@joshblack the output of your zoned theming looks to have some typos in it and is it also intended to have both dark and light use the same colors. I think it would be clearer if it used different colors in the example.

**Comment by joshblack** [comment]
Hah, good catch, I blame copy paste 😂

**Comment by mattrosno** [comment]
Can we author:

```css
.selector {
  color: var(--token-01, #000000);
}
```

And tell teams if they want IE11 fallbacks, to use the PostCSS plugin that generates:

```css
.selector {
  color: #000000;
  color: var(--token-01, #000000);
}
```

https://github.com/postcss/postcss-custom-properties

That would allow our source to remain free of IE11 fallbacks.

(CRA does this behind the scenes if IE11 is included in browserslist config.)

**Comment by mattrosno** [comment]
I think it'd be great to for variables to remain Sass variables, and then we have a transformation based on the feature flag. E.g. tokens like:

```scss
$token-01: pink !default;
$token-02: blue !default;
```

Then save those in a map that is iteratable:

```scss
$tokens: (
  'token-01': $token-01,
  'token-02': $token-02
) !default;
```

Then in your build step, if the custom property feature flag is enabled, do the transformation:

```scss
@each $key, $value in $tokens {
  $tokens: map-merge(
    $tokens,
    (
      $key: var(--#{$prefix}--#{$key}, #{$value}),
    )
  );
}
```

Now, the value of `$token-01` is no longer `pink`, it's `var(--bx--token-01, pink)`. The Sass:

```scss
.selector {
  background: $token-01;
}
```

Becomes CSS:

```css
.selector {
  background: var(--bx--token-01, pink);
}
```

And after PostCSS'ed:

```css
.selector {
  background: pink;
  background: var(--bx--token-01, pink);
}
```

P.S. CSS custom properties should be prefixed to prevent run-time collisions with 3rd-party styling or scenarios when there's a need to use multiple Carbon versions on the same page.

**Comment by joshblack** [comment]
@mattrosno I think you're defining the ideal with the postcss fallback, definitely think we should get there in v11 or when we drop IE11. Maybe we just implement this behavior behind a feature flag and suggest that is the strategy moving forward?

Some of these solutions are operating under the idea that we both want to:

- Ship custom properties without a feature flag (not a hard requirement)
- Not break existing consumers who expect IE11 support, or are targetting browsers that may not understand CSS Custom Properties (hard requirement in stable release channel)

**Comment by joshblack** [comment]
We're going to move forward with the following and get feedback on if the sass build pipeline is needed:

```scss
.selector {
  // Tokens are namespaced with --c-
  color: var(--c-token-01, $token-01);
}
```

And we will polyfill our output `scss` directory with if folks justify it as needed

```scss
.selector {
  color: $token-01;
  color: var(--c-token-01, $token-01);
}
```
