### ISSUE TITLE
Add build pipeline for `carbon-components` Sass files for CSS Custom Property fallback

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4001]
We're looking to add support for CSS Custom Property to our source files. This format will follow:

```diff
.#{$prefix}--component-name {
-  color: $token-01;
+  color: var(--token-01, $token-01);
}
```

However, we can't ship CSS Custom Properties as a direct replacement as this could break existing users during a minor bump. As a result, we need to introduce a build pipeline that will take in our source sass files and do the following transform:

```scss
// Input
.#{$prefix}--component-name {
  color: var(--token-01, $token-01);
}

// Output
.#{$prefix}--component-name {
  color: $token-01;
  color: var(--token-01, $token-01);
}
```

Thankfully, we can use a combination of `postcss`, `postcss-scss`, and `postcss-css-variables` to accomplish this for our output `scss` directory.

This will need to be introduced in the `sass:source` gulp task:

```js
gulp.task('sass:source', () =>
  gulp.src('./src/**/*.scss').pipe(gulp.dest('scss'))
);
```

Most likely with the following modification:

```js
const cssVariables = require('postcss-css-variables');
const scss = require('postcss-scss');

gulp.task('sass:source', () =>
  gulp
    .src('./src/**/*.scss')
    .pipe(postcss([cssVariables({ preserve: true })], { parsers: scss }))
    .pipe(gulp.dest('scss'))
);
```

_Note: we use `postcss-css-variables` instead of the alternative as it can handle `$token-01` as a value type_
