### ISSUE TITLE
Carbon layout media query mixins Incorrect

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/carbon#4020]
The carbon layout mixin carbon--breakpoint-down incorrectly handles small breakpoints.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `@carbon/layout`

## Detailed description

> Describe in detail the issue you're having.

Setting styles to work below the smallest size does not work.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

To be able to set styles only applied at the smallest size.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.6.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See https://codesandbox.io/s/carbon-breakpoint-mixin-issue-q8vgx

Define styles starting with the largest and working down
e.g. 
```css
.a-box {
  &::after {
    font-size: 24px;
    content: "I am default sized content";
  }

  @include carbon--breakpoint-down("max") {
    &::after {
      content: 'I am content for "max" sized screens';
    }
  }

  @include carbon--breakpoint-down("md") {
    &::after {
      content: 'I am content for "md" sized screens';
    }
  }

  @include carbon--breakpoint-down("sm") {
    &::after {
      color: red;
      content: 'I am content for "sm" sized screens';
    }
  }
}
```

The last style should only be applied below "sm" sizes but is applied in all the time.
