### ISSUE TITLE
Create CSS Custom Properties feature flag

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4033]
We should create a feature flag for enabling css custom properties, probably `enable-css-custom-properties` following the trend of Chrome feature flags (and could set a precedent in the future).

When this flag is enabled, we should redefine our tokens to correspond to the CSS Custom Property equivalent of their values, meaning:

```scss
// Before
$interactive-01: $blue-60
// After
$interactive-01: var(--cds-interactive-01, $blue-60);
```

**Comment by joshblack** [comment]
@emyarod you wanna take this on? Or are you more into the elements work? 👀

**Comment by emyarod** [comment]
@joshblack sure I can take this on

**Comment by emyarod** [comment]
just want to clarify (we can update the original ticket based on the discussions we've had offline as well), when the feature flag is enabled we do not want to provide fallbacks for browsers that do not support CSS custom properties? and by default we will provide both fallback value and custom property?

input sass:

```scss
$red: #f00;

.component {
  color: $red;
}
```

output css:

```css
/* feature flag disabled */
.component {
  color: #f00;
  color: var(--red, #f00);
}

/* feature flag enabled */
.component {
  color: var(--red, #f00);
}
```

**Comment by joshblack** [comment]
@emyarod I think right now the idea is:

```scss
// Carbon style
.my-selector {
  color: $token-01;
}

// Loading by default
@import 'path/to/carbon';

// Output
.my-selector {
  color: #000000;
}

// Loading with flag
$feature-flags: (enable-css-custom-propertes: true);
@import 'path/to/carbon';

// Output
.my-selector {
  color: (--cds-token-01, #000000);
}
```
