### ISSUE TITLE
Add constraint for icon size based on type pairing

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#4136]
We currently have a constraint in our design system where icons are paired with the line height of the given text that it sits next too. We need to make sure that this constraint exists in code.

For example, if we have an icon adjacent to text with 14px font size and 16px line height, we could map the SVG artboard size to 16px. Similarly, we need to map the line-height for 20/24/32 assets, as well.

Under the hood, this may be a helper function that we add into the codebase in a `_constraints.scss` file (name TBD) that looks like:

```scss
@function strip-unit($number) {
  @if type-of($number) == 'number' and not unitless($number) {
    @return $number / ($number * 0 + 1);
  }

  @return $number;
}

$sizes: (16, 20, 24, 32);
@function get-icon-size($token, $sizes: $sizes) {
  $line-height: strip-unit(map-get($token, 'line-height'));
  $icon-size: null;
  
  @each $size in $sizes {
    @if $icon-size == null {
      @if $size <= $line-height {
        $icon-size: $size;
      }
    }
  }
  
  @return $icon-size * 1px;
}

$token: (line-height: 16px);

.icon {
  width: rem(get-icon-size($token));
  height: rem(get-icon-size($token));
}
```

This isn't to say that this is how it must be implemented, just as an idea for what kind of logic we want to offer (pairing line height with icon artboard sizes) and how it might be used in our selectors.
