### ISSUE TITLE
[theming]: If a component relies on body font color, it can't be themed

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#4545]
Checkbox label relies on body font color: `var(--cds-text-01, #161616)`

If that token is not defined in body, the default is used.

To reproduce: add a g100 theme to a wrapper and wrap the checkbox component. The text will use the default (#161616) since it's looking on body rather than the nearest `--cds-text-01`

Add the following to your wrapper, the label will pick up the wrappers text color
```css
[class*='--checkbox-label'] {
  color: var(--cds-text-01, #161616);
}
```

Problems:
- [ ] Checkbox label
- [ ] AccordionItem content
