### ISSUE TITLE
Toggle night mode on the fly

### ISSUE THREAD

**Issue by salewan** [carbon-design-system/carbon#4730]
Hi. Is there a way to switch themes on the fly. I use react components and didn't find any information about this topic.
Thank you in advance.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

**Comment by asudoh** [comment]
Hi 👋 I think you can integrate [dark theme's CSS standard](https://drafts.csswg.org/mediaqueries-5/#descdef-media-prefers-color-scheme) with our custom properties support (though I haven't tried in person):

```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

@import 'carbon-components/scss/globals/scss/css--helpers';
@import 'carbon-components/scss/globals/scss/vendor/@carbon/elements/scss/themes/mixins';

@media (prefers-color-scheme: dark) {
  :root {
    @include carbon--theme($carbon--theme--g100, true);
  }
}
```

Please refer to #4100 and its preceding changes for more details. CC @emyarod
