### ISSUE TITLE
[list-box] recent changes cause styled dropdowns to be permanently open

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon#6002]
Our styles used max-height to define the maximum expansion of a list-box. Developers overriding that max-height property found that their values were now permanent, effectively making their dropdowns permanently open.

https://github.com/carbon-design-system/carbon/pull/5810/files#diff-4e29779c2451f455d2b3f80a885d7d63R435

Our max-height of 0 should take precedent when the dropdown is not expanded.

**Comment by moficodes** [comment]
I am seeing this as well. Is there any workaround to this?

**Comment by bourdakos1** [comment]
@ here

**Comment by tw15egan** [comment]
A temporary workaround

```css
.bx--list-box .bx--list-box__field[aria-expanded='false'] + .bx--list-box__menu  {
    max-height: 0;
}
```
