### ISSUE TITLE
Need options for tooltips to display on a timer

### ISSUE THREAD

**Issue by CynZhang** [carbon-design-system/carbon#6178]
### Summary

We'd like the tooltip component to have options to set a delay on hover to avoid unintentional activation.

### Justification
The native tooltips that we are using have a short delay, but carbon's tooltip is missing this feature. The tooltip always pops up right away, it makes the user experience slightly different when replacing them. The delay would help to avoid accidental activations, and make users feel more in control. 

### Desired UX and success metrics

The expected behavior of the icon tooltip would be when user mouse over the icon or the target area, if the cursor remains stopped for no less than 0.5 seconds (custom defined), then show the tooltip content.

**Comment by emyarod** [comment]
you should be able to adjust the animation properties with CSS, so something like this for example:

```css
.bx--tooltip__trigger::before,
.bx--tooltip__trigger .bx--assistive-text {
  animation-delay: 500ms;
}
```

**Comment by CynZhang** [comment]
@scottdickerson maybe give this a try?

**Comment by scottdickerson** [comment]
@emyarod I'm not having any luck with that, not sure that an actual css animation is getting triggered to show the tooltip.  Seems like maybe it's just getting transformed

**Comment by emyarod** [comment]
@scottdickerson just to clarify are you using the icon/definition tooltips or the interactive tooltip? I assume it is the former because of the reference to hover interactions in the issue description

**Comment by scottdickerson** [comment]
Yes it’s the hasIconOnly ghost button tooltip

**Comment by emyarod** [comment]
I think I see the cause of the issue now, the `clip` property most likely needs to be included in the animation (not just `opacity` alone)

**Comment by emyarod** [comment]
it turns out in my testing I was actually adjusting the `*-duration` properties instead of `*-delay`, not sure if that's a viable workaround in the meantime. at the moment it's not clear why the `*-delay` properties don't seem to be working

```css
.bx--tooltip__trigger::before {
  transition-duration: 2s;
}
.bx--tooltip__trigger .bx--assistive-text {
  animation-duration: 2s;
}
```
