### ISSUE TITLE
TableToolbarAction does not provide a means to resize the overflow menu

### ISSUE THREAD

**Issue by darosale** [carbon-design-system/carbon#6229]
### Summary

TableToolbarAction needs a method to dynamically resize the overflow menu.

### Justification

When a menu item text is longer than the fixed width of the menu, it can be truncated or wrapped. There are languages that can truncate or wrap mid word which may change the meaning of the text.

### "Must have" functionality

The TableToolbarAction component should allow for users to define a width for the overflow menu.

**Comment by emyarod** [comment]
I'm not sure we will add an option for dynamically resizing menus but this should be achievable with CSS like

```css
.bx--overflow-menu-options {
  width: auto;
}

.bx--overflow-menu-options__btn {
  max-width: auto;
}
```
