### ISSUE TITLE
Button: Need to avoid rem() call on variables

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon#6469]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

[`button/_mixins.scss`](https://github.com/carbon-design-system/carbon/blob/v10.15.0/packages/components/src/components/button/_mixins.scss#L23) code runs `rem()` conversion against a variable (`$button-height`). This causes an error when such variable contains CSS custom properties.

> Is this issue related to a specific component?

Yes, button.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Doing `$button-height: 3rem !default` at [`_theme-tokens.scss`](https://github.com/carbon-design-system/carbon/blob/v10.15.0/packages/components/src/globals/scss/_theme-tokens.scss#L91) to ensure the button height is defined in `rem` unit.

## Steps to reproduce the issue

Something like below, as seen in: https://codesandbox.io/s/github/asudoh/carbon-components/tree/test-button/packages/components/examples/codesandbox

```scss
$button-height: var(--button-height);

@import 'carbon-components/scss/components/button/button';

#app {
  --button-height: 5rem;
}
```
