### ISSUE TITLE
Modal position inside UIShell with a Header

### ISSUE THREAD

**Issue by albertms10** [carbon-design-system/carbon#7015]
### Summary

As described in https://github.com/IBM/carbon-components-svelte/issues/309, the position of a modal opened inside a UIShell Content with Header hides some modal elements in some scenarios.

### Justification

In desktop, as the screen size is big enough, the modal is just clipped some pixels in its bottom side, but on mobile, it hides the footer action buttons, making it unusable.

### Desired UX and success metrics

The modal should be positioned according to the actual `Content` size, taking the `Header` height into account.

### "Must have" functionality

—

### Specific timeline issues / requests

—

### Available extra resources

A possible workaround like this one could fix the issue, leading to a properly centred Modal window:

```css
/* for explanatory purposes */
:root {
  --header-height: 3rem;
}

.bx--modal-container {
  position: relative;
  bottom: calc(var(--header-height) / 2);
  height: calc(90% - var(--header-height));
}
```

_Carbon is a collaborative system. We encourage teams to build components and
submit them for integration as either add-ons or core components._
