### ISSUE TITLE
Missing breakpoints after update from 8.12.0 to 8.13.0

### ISSUE THREAD

**Issue by jamesvclements** [carbon-design-system/carbon#724]
When using v8.12.0, all the breakpoints like `bp--xs--major` work fine, and I can view our source CSS with the translated `px` values.

After updating to v8.13.0, the breakpoints are missing. The source then looks like:
```css
.bx--breadcrumb {
  font-size: 0.875rem;
  font-family: "ibm-plex-sans", Helvetica Neue, Arial, sans-serif;
  display: inline;
}

@media (min-width: bp--xs--major) { <-- missing breakpoint
  .bx--breadcrumb {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-wrap: wrap;
        flex-wrap: wrap;
```

The [diff](https://github.com/carbon-design-system/carbon-components/pull/565/files) for the release shows a different `yarn.lock` - maybe that's related 🤔
