### ISSUE TITLE
Tag component with css variables

### ISSUE THREAD

**Issue by moczolaszlo** [carbon-design-system/carbon#7800]
Hi!

As I see, this example not working: https://www.carbondesignsystem.com/components/tag/code
If I change the theme, the colors don't react, because the css custom variable is undefined and always the fallback is active.
We are facing the same problem, because if we add this to our root scss, it's don't contains the vars for tag:
```scss
@include carbon--theme($carbon--theme--g100, true);
```

Is this intentional? Or is there a mixin/function to get this variables?

For the quick fix, I made a small mixin:
```scss
@mixin get-variables($globalTheme, $tokens) {
	@each $key, $options in $tokens {
		$values: map-get($options, 'values');
		@each $valueObject in $values {
			$theme: map-get($valueObject, 'theme');
			$value: map-get($valueObject, 'value');
			@if $theme == $globalTheme {
				@include custom-property($key, $value);
			}
		}
	}
}
```
Before this we include the tokens of tag (https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/tag/_tokens.scss), and we include our mixin like this:
```scss
.root-element {
  @include get-variables($carbon--theme--g100, $tag-colors);
}
```

And it's will generate:
```css
.root-element {
  --cds-tag-background-red: #ffd7d9;
  --cds-tag-color-red: #750e13;
  --cds-tag-hover-red: #ffb3b8;
...
}
```
What do you think about it?
