### ISSUE TITLE
Dark mode - InlineNotification lowContrast text color needs update

### ISSUE THREAD

**Issue by finken2** [carbon-design-system/carbon#8196]
Using dark mode (gray-100), the text for InlineNotification w/ lowContrast stays white, and is unreadable:
![image](https://user-images.githubusercontent.com/50754824/112634968-9a585300-8e11-11eb-92c1-722c8991203d.png)

```
.bx--inline-notification--low-contrast {
    color: var(--cds-text-01, #161616);
}
```
cds-text-01 is `#f4f4f4`

**Comment by tw15egan** [comment]
Thanks for much for taking the time to make this issue, I'm not seeing the issue on some recent deploy previews: https://deploy-preview-8213--carbon-components-react.netlify.app/?path=/story/components-notifications--inline

Could you share some steps to reproduce the problem you noted over in [CodeSandbox](https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox)? This will help us figure out what's going on here.

**Comment by finken2** [comment]
Interesting, yeah, looks good in that deploy preview you linked. Perhaps it's been fixed but not made its way through PAL yet? I'll poke around a bit and get back to you.

**Comment by tw15egan** [comment]
I believe this has come up recently and should be fixed on latest: 

https://github.com/carbon-design-system/carbon/issues/7857
 - https://github.com/carbon-design-system/carbon/issues/7857#issuecomment-784463409


Updated guidance 
https://github.com/carbon-design-system/carbon/pull/7808

**Comment by finken2** [comment]
@tw15egan I think we need to update PAL to do some of that emitting as mentioned in #7808.  I'm attempting to do that, and after adding the emit code, i do now see the classes in the theme, but somehow, now the styles are no longer referencing them:
![image](https://user-images.githubusercontent.com/50754824/113062189-5b176280-9181-11eb-8f3a-e956af5b6e81.png)

Any thoughts on what could be happening there? Before my changes, the tokens were being referenced, but weren't there. Now they're there, and not being referenced.

**Comment by tw15egan** [comment]
Just to be sure, you are doing something similar to this? 

```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

@import '~carbon-components/scss/globals/scss/theme';
@import '~carbon-components/scss/globals/scss/component-tokens';

@import '~carbon-components/src/components/tag/tag';
@import '~carbon-components/src/components/notification/notification';

:root {
  @include carbon--theme($carbon--theme--g100, true) {
    @include emit-component-tokens($tag-colors);
    @include emit-component-tokens($notification-colors);
  }
}
```

Is it possible to reproduce the issue so we can take a deeper look?
