### ISSUE TITLE
`DataTable[size="short"]` breaks alignment of `Select`s arrow icon: 

### ISSUE THREAD

**Issue by kubijo** [carbon-design-system/carbon#8206]
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Is this issue related to a specific component?
- `DataTable`
- `Select`

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/eager-taussig-lfolm?file=/src/index.js

## Additional information

Offending style (works fine without it):
```css
.bx--data-table--short .bx--select__arrow {
    top: 0.875rem;
}
```

**Comment by kubijo** [comment]
This seems to be wrong as well: 

```css
.bx--data-table--short select {
    padding: 0.45rem 2.75rem 0.45rem 1rem;
}
```

In general, it's very fragile to patch the inner styling of other components in such a manner and I have a hunch that `DataTable` will have many more of these…

**Comment by kubijo** [comment]
Also, I get inconsistent sizing in the table row if not all rows contain `Select`.
This is because `Select[size="sm"]` has a height of `2rem` & stretches it's row height.

```css
.bx--select-input--sm {
    height: 2rem;
    max-height: 2rem;
}
```

![image](https://user-images.githubusercontent.com/11244314/112816935-31c3dd00-9082-11eb-9560-5092bf352161.png)
