### ISSUE TITLE
`@include carbon--type-style` doesn't work with `enable-css-custom-properties` on

### ISSUE THREAD

**Issue by s100** [carbon-design-system/carbon#8668]
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`
- [x] `@carbon/type`

## Detailed description

> Describe in detail the issue you're having.

I'm trying to isolate https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/733. When trying to use `@carbon/type`'s SCSS resources, I find the following Sass:

```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

@import '@carbon/type/scss/styles';

.test-btn {
  @include carbon--type-style('expressive-heading-05');
}
```

fails to compile using the [`sass`](https://www.npmjs.com/package/sass) package:

```
    ERROR in ./index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/fast-sass-loader/lib??ref--4-2!./index.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: (md: (font-size: 2.25rem, font-weight: 300, line-height: 1.22), lg: (font-size: 2.625rem, line-height: 1.19), xlg: (font-size: 3rem, line-height: 1.17), max: (font-size: 3.75rem)) isn't a valid CSS value.
         ╷
    1164 │       #{$value}
         │         ^^^^^^
         ╵
      index.scss 1164:9  custom-properties()
      index.scss 1198:7  carbon--type-style()
      index.scss 1209:3  root stylesheet
```

> Is this issue related to a specific component?

No.

> What browser are you working in?

None, this is at build time.

> What version of the Carbon Design System are you using?

10. `@carbon/type@10.27.0`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

N/A

## Steps to reproduce the issue

`index.js`:

```js
import './index.scss'
console.log('hello world')
```

`index.scss`:

```scss
$feature-flags: (
  enable-css-custom-properties: true,
);
@import '@carbon/type/scss/styles';
.test-btn {
  @include carbon--type-style('expressive-heading-05');
}
```

`webpack.config.js`:

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
  mode: 'production',
  entry: {
    main: './index.js'
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: [{
        loader: MiniCssExtractPlugin.loader
      }, {
        loader: 'css-loader'
      }, {
        loader: 'fast-sass-loader',
        options: {
          includePaths: ['node_modules']
        }
      }]
    }]
  },
  plugins: [new MiniCssExtractPlugin()]
}
```

Command line:

```sh
npm install \
  webpack \
  webpack-cli \
  mini-css-extract-plugin \
  css-loader \
  fast-sass-loader \
  sass \
  @carbon/type
npx webpack
```

## Additional information

I think the problem may lie [here](https://github.com/carbon-design-system/carbon/blob/48deedf2fb7a343594ed844d6c852c9108a3eb53/packages/type/scss/_styles.scss#L702-L710):

```scss
    @if global-variable-exists('feature-flags') and
      map-get($feature-flags, 'enable-css-custom-properties')
    {
      @include custom-properties($name, $token);
    } @else {
      // Otherwise, we just include all the property declarations directly on the
      // selector
      @include properties(map-remove($token, 'breakpoints'));
    }
```

Shouldn't you be stripping the `breakpoints` property out of `$token` on both of those branches?
