### ISSUE TITLE
Gray 80 low contrast notification incorrect background color?

### ISSUE THREAD

**Issue by metonym** [carbon-design-system/carbon#9106]
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

It appears that the background color for a Gray 80 theme low contrast notification is too light. The g90/g100 themes use a dark background with light text.

<img width="1059" alt="Screen Shot 2021-07-03 at 4 52 55 AM" src="https://user-images.githubusercontent.com/10718366/124353412-389b4800-dbbb-11eb-81e4-f3894f4a5d91.png">

**g80**

```css
.bx--inline-notification--low-contrast.bx--inline-notification--error {
    border-left: 3px solid var(--cds-support-error,#da1e28);
    background: var(--cds-notification-background-error,#fff1f1);
}
```

**g90**

```css
.bx--inline-notification--low-contrast.bx--inline-notification--error {
    border-left: 3px solid var(--cds-support-error,#da1e28);
    background: var(--cds-notification-background-error,#fff1f1);
}
```

## Possible solution

A possible solution may be to add the `g80` theme layer tokens to `components/src/components/notification/_tokens.scss`: https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/notification/_tokens.scss

See PR #9107 

## Steps to reproduce the issue

1. Visit https://carbon-svelte.vercel.app/components/InlineNotification?theme=g80#low-contrast
