### ISSUE TITLE
Fix bug with setting theme in compatability mode resulting in a noop

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon#9617]
This issue was originally reported by @janhassel where the compat theme was not able to have its value changed.

Code to reproduce:

```scss
@use '@carbon/react/scss/reset';
@use '@carbon/react/scss/compat/themes';
@use '@carbon/react/scss/compat/theme' with (
  $theme: themes.$g90
);

body {
  background: theme.$background;
  color: theme.$text-primary;
}
```

Here, we expected the tokens to use values from the g90 theme but they use the value from the white theme instead. It seems like this is related to the issue Jan reported in that the theme would not allow you to correctly retrieve `interactive-01` as a token because the themes were not being merged
